# Generated by Django 2.1.5 on 2019-03-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190207_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(default='kmovie@list.ru', max_length=70),
        ),
        migrations.AddField(
            model_name='user',
            name='user_pass',
            field=models.CharField(default='1111', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.CharField(default='068213927', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_surname',
            field=models.CharField(default='Petrov', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='Kristina', max_length=100),
        ),
    ]
