# Generated by Django 2.1.5 on 2019-03-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190326_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encodings',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
