# Generated by Django 2.1.5 on 2019-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190328_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
