# Generated by Django 2.1.5 on 2019-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190404_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Uploaded image'),
        ),
    ]
